"""
scripts/generate_dnsmasq_configs.py
Tạo file config dnsmasq cho DHCP server (DC-DHCP01) và DNS server (DC-DNS01).
Đọc từ config/services.yaml và xuất ra /tmp/dnsmasq_dhcp.conf, /tmp/dnsmasq_dns.conf

Cách dùng:
  python3 scripts/generate_dnsmasq_configs.py
"""

import sys
import os
import yaml

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

SERVICES_CONFIG_PATH = os.path.join(os.path.dirname(__file__), '..', 'config', 'services.yaml')


def generate_dnsmasq_dhcp(dhcp_cfg):
    """Tạo config dnsmasq cho DHCP server."""
    dns_ip  = dhcp_cfg['dns_server']
    ntp_ip  = dhcp_cfg['ntp_server']
    domain  = dhcp_cfg['domain']
    lease   = dhcp_cfg['lease_time']

    lines = [
        '# dnsmasq DHCP Server — DC-DHCP01',
        '# Generated by scripts/generate_dnsmasq_configs.py',
        '',
        'port=0                     # Tắt DNS trên DHCP server (DNS riêng ở DC-DNS01)',
        f'domain={domain}',
        f'dhcp-option=6,{dns_ip}    # Option 6: DNS server',
        f'dhcp-option=42,{ntp_ip}   # Option 42: NTP server',
        f'dhcp-leasefile=/tmp/dnsmasq_dhcp.leases',
        f'pid-file=/tmp/dnsmasq_dhcp.pid',
        'log-dhcp',
        '',
        '# DHCP Pools:',
    ]

    for pool in dhcp_cfg['pools']:
        subnet  = pool['subnet']
        r_start = pool['range_start']
        r_end   = pool['range_end']
        gw      = pool['gateway']
        desc    = pool.get('description', '')

        lines += [
            f'# {desc} — VLAN {pool["vlan"]}',
            f'dhcp-range={r_start},{r_end},{lease}',
            f'dhcp-option=tag:{pool["vlan"]},3,{gw}    # Gateway',
            '',
        ]

    return '\n'.join(lines)


def generate_dnsmasq_dns(dns_cfg):
    """Tạo config dnsmasq cho DNS server."""
    zone    = dns_cfg['zone']
    upstream = dns_cfg.get('upstream_dns', '8.8.8.8')
    cache   = dns_cfg.get('cache_size', 1000)

    lines = [
        '# dnsmasq DNS Server — DC-DNS01',
        '# Generated by scripts/generate_dnsmasq_configs.py',
        '',
        'port=53',
        f'domain={zone}',
        f'server={upstream}',
        f'cache-size={cache}',
        'local-ttl=60',
        f'pid-file=/tmp/dnsmasq_dns.pid',
        f'log-queries',
        '',
        '# A Records:',
    ]

    for record in dns_cfg['records']:
        fqdn = record['fqdn']
        ip   = record['ip']
        desc = record.get('alias', record.get('description', ''))
        lines.append(f'address=/{fqdn}/{ip}    # {desc}')

    return '\n'.join(lines)


def main():
    with open(SERVICES_CONFIG_PATH) as f:
        cfg = yaml.safe_load(f)

    output_dir = '/tmp'

    # DHCP Primary config
    dhcp_conf = generate_dnsmasq_dhcp(cfg['dhcp'])
    dhcp_path = os.path.join(output_dir, 'dnsmasq_dhcp.conf')
    with open(dhcp_path, 'w') as f:
        f.write(dhcp_conf)
    print(f'[OK] {dhcp_path}')

    # DHCP Backup config (DC-DHCP02)
    dhcp2_conf = dhcp_conf.replace('DC-DHCP01', 'DC-DHCP02').replace('dnsmasq_dhcp.pid', 'dnsmasq_dhcp2.pid').replace('dnsmasq_dhcp.leases', 'dnsmasq_dhcp2.leases')
    dhcp2_path = os.path.join(output_dir, 'dnsmasq_dhcp2.conf')
    with open(dhcp2_path, 'w') as f:
        f.write(dhcp2_conf)
    print(f'[OK] {dhcp2_path}')

    # DNS config
    dns_conf = generate_dnsmasq_dns(cfg['dns'])
    dns_path = os.path.join(output_dir, 'dnsmasq_dns.conf')
    with open(dns_path, 'w') as f:
        f.write(dns_conf)
    print(f'[OK] {dns_path}')

    print(f'\nĐã tạo DHCP (Primary + Backup) và DNS config trong {output_dir}/')


if __name__ == '__main__':
    main()
